"""empty message

Revision ID: 6447bacd33d6
Revises: 
Create Date: 2022-10-06 02:48:07.279191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6447bacd33d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('role', sa.String(length=128), server_default='user', nullable=True),
    sa.Column('alternative_id', sa.String(length=128), server_default='b755fc36fbaf4918909b7e69aa90d1c1', nullable=True),
    sa.Column('is_active_user', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id', 'username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('server')
    # ### end Alembic commands ###
