"""empty message

Revision ID: 928980f91c8d
Revises: 6447bacd33d6
Create Date: 2022-10-06 13:27:29.974377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928980f91c8d'
down_revision = '6447bacd33d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('createDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'createDate')
    # ### end Alembic commands ###
