"""empty message

Revision ID: 98ac3cf90110
Revises: aaf133126846
Create Date: 2022-10-11 01:17:24.437153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ac3cf90110'
down_revision = 'aaf133126846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updateDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updateDate')
    op.drop_column('user', 'createDate')
    # ### end Alembic commands ###
