"""empty message

Revision ID: aaf133126846
Revises: 928980f91c8d
Create Date: 2022-10-06 13:29:01.462550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf133126846'
down_revision = '928980f91c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('updateDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'updateDate')
    # ### end Alembic commands ###
